version: '2'
services:
  nodered:
    image: nodered/node-red-docker:rpi-v8
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
    links:
      - mosquitto
    restart: always

  mosquitto:
    image: monstrenyatko/rpi-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mosquitto-config:/config:ro
      - ./mosquitto-data:/data
      - ./mosquitto-log:/log
    restart: always



